method: bayes
metric:
  goal: maximize
  name: average_test_jaccard_index

parameters:
  LEARNING_RATE:
    min: 0.0001
    max: 0.01

program: train.py
command:
  - ${env}
  - python
  - ${program}
  - configs.config
  - --tune
  - --num_trials
  - "2"