method: bayes
metric:
  goal: maximize
  name: average_test_jaccard_index

parameters:
  GAUSSIAN_NOISE_PROB:
    values: [0.2, 0.3, 0.4, 0.5]
  GAUSSIAN_NOISE_STD:
    values: [0.05, 0.1, 0.2, 0.3]
  SATURATION_LIMIT:
    values: [0.1,0.2,0.3]
command:
- python
- train.py
- configs.dsi
- --tune 
- --num_trials
- 2
